version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: exploradoressemfronteiras
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: esf_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: exploradoressemfronteiras
      DB_PASSWORD: 123456
      DB_NAME: esf_db

volumes:
  pgdata:
